### PR TITLE
Fixed alt. server query returns 2 or more rows when have 3 tissues in…

### LINKED ISSUE #17: Alt. server query returns N/A when the player count is much larger than server max player
I set up a bridge server with soft-limit of 0 player and server max player of 1. So it will always searching for the lowest player count server in the organ.
However when the player count raises pass the max player count, say 7/1, the Recommended alt. server starts to turn into N/A.
If I set up a server in that organ with 0/1, soft limit 0 like before, it always point the right server with no problem.
Basically, the soft limit must much lower than the max player in order for the balance system to be worked. And now I don't know how to set up a bridge server anymore..

I'm not gonna lie, but when I have 3 servers in the organ include this bridge one, the problem happens. When I have only 2 include the bridge, the player was transfered, but stuck with the Syncing texture pack. I did successfully transfered if one player is transfered, once at a time, but the heavy transfer seems to make all players stuck. Please help.

### PR DESCRIPTION
**Pull request by intagaming**
… an organ

Fixes #17 
So I debugged the query code just above the code I've edited and they returns 2 servers that can be transferred to. And this line popped up as it making the main server said that "Organ is full!".

Tested and working right now, seems no problem.

### CODE REVIEW

**Comment by SOF3** [comment]
Shouldn't it be just a `LIMIT 1` in the query?

**Comment by SOF3** [comment]
I see the problem condition to be that the other two servers have the exactly same number of empty slots, right?

**Comment by intagaming** [comment]
Hnmm I'm not sure.. Seems like that, maybe the `LIMIT 1` will do!
Trying to test that.
Oh and please edit the code too, im not MySQL professional, with that complex level.

**Comment by intagaming** [comment]
I assume that it will work. Here's my test result:
Old code, i ran many times to see 2 rows, when 2 servers have the same available slot obviously:
image
New code, should returns 2 servers separately as I run many times:
image
image

**Comment by SOF3** [comment]
Thanks, I'll test later.

**Comment by SOF3** [comment]
Fixes #17

**Pull request merged**
