### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by Awzaw**

### CODE REVIEW

**Comment by AvgZing** [comment]
This was meant to be serverauth, as that is what they support.

**Comment by dktapps** [comment]
since it's SimpleAuth single session integration `SimpleAuthSingleSessionIntegration`
and it's checking for an instance of SimpleAuth... this is indeed a bug.

**Comment by AvgZing** [comment]
Oh. I was thinking that serverauth is made by one of their "allies" (kinda) and they weren't supporting simpleauth. But @dktapps your point is valid.

**Comment by SOF3** [comment]
Oops, right.

**Comment by SOF3** [comment]
Oops, right, thanks for pointing that out. I forgot to change that while copying code :smile:

I have never tested the singleSession module anyway.

**Pull request merged**
